replicaCount: 1

image:
  repository: liavhackmon/rick-morty-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
      paths:
        - path: /rickmorty
          pathType: Prefix

resources: {}

nodeSelector: {}

tolerations: []

affinity: []
serviceAccount:
  create: true
  name: ""
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


