apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rickmorty-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /rickmorty
        pathType: Prefix
        backend:
          service:
            name: rickmorty-service
            port:
              number: 80
