name: CI/CD Rick and Morty App

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image (local only)
      run: docker build -t liavhackmon/rick-morty-app:latest ./task2

    - name: Set up Kubernetes cluster with kind
      uses: engineerd/setup-kind@v0.6.1
      with:
        version: v0.20.0
        wait-for-ready: true
        name: rickmorty-cluster

    - name: Load Docker image into kind cluster
      run: kind load docker-image liavhackmon/rick-morty-app:latest --name rickmorty-cluster

    - name: Deploy Kubernetes manifests
      run: |
        kubectl apply -f ./task2/yamls/Deployment.yaml
        kubectl apply -f ./task2/yamls/Service.yaml
        kubectl apply -f ./task2/yamls/Ingress.yaml

    - name: Wait for deployment rollout
      run: kubectl rollout status deployment/rickmorty --timeout=90s

    - name: Run API tests
      run: |
        sleep 10
        curl -f http://localhost/rickmorty/healthcheck
        curl -f http://localhost/rickmorty/characters

