name: Kubernetes CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: liavhackmon/rick-morty-app:latest
        file: task2/Dockerfile
        context: task2  

    - name: Set up kind (Kubernetes IN Docker) cluster
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.20.0

    - name: Load Docker image into kind cluster
      run: kind load docker-image liavhackmon/rick-morty-app:latest

    - name: Deploy Kubernetes manifests
      run: |
        kubectl apply -f ./yamls

    - name: Wait for deployment rollout
      run: |
        kubectl rollout status deployment/rickmorty-deployment --timeout=2m

    - name: Run healthcheck test
      run: |
        kubectl port-forward svc/rickmorty-service 8080:80 &
        sleep 5
        curl -f http://localhost:8080/rickmorty/healthcheck

