name: CI/CD Rick and Morty App

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./task2
        file: ./task2/Dockerfile
        push: true
        tags: liavhackmon/rick-morty-app:latest

    - name: Set up Kubernetes cluster
      uses: manusa/actions-setup-minikube@v2.6.0
      with:
        minikube version: 'latest'
        kubernetes version: 'latest'

    - name: Load Docker image into Minikube
      run: minikube image load liavhackmon/rick-morty-app:latest

    - name: Deploy Kubernetes manifests
      run: |
        kubectl apply -f ./task2/yamls/Deployment.yaml
        kubectl apply -f ./task2/yamls/Service.yaml
        kubectl apply -f ./task2/yamls/Ingress.yaml

    - name: Wait for deployment rollout
      run: kubectl rollout status deployment/rickmorty --timeout=90s

    - name: Run API tests
      run: |
        sleep 10
        curl -f http://localhost/rickmorty/healthcheck
        curl -f http://localhost/rickmorty/characters


