name: CI/CD Rick and Morty App

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t liavhackmon/rick-morty-app:latest ./task2

    - name: Push Docker image
      run: docker push liavhackmon/rick-morty-app:latest

    - name: Set up kind cluster
      uses: helm/kind-action@v1.8.0
      with:
        cluster_name: rickmorty-cluster

    - name: Pull image from Docker Hub
      run: |
        docker pull liavhackmon/rick-morty-app:latest
        kind load docker-image liavhackmon/rick-morty-app:latest --name rickmorty-cluster

    - name: Deploy to kind
      run: |
        kubectl apply -f ./task2/yamls/Deployment.yaml
        kubectl apply -f ./task2/yamls/Service.yaml
        kubectl apply -f ./task2/yamls/Ingress.yaml
        kubectl rollout status deployment/rickmorty --timeout=90s

    - name: Debug cluster state
      run: |
        echo "--- Pods ---"
        kubectl get pods -o wide
        echo "--- Services ---"
        kubectl get svc
        echo "--- Ingress ---"
        kubectl get ingress

    - name: Port forward & Test endpoints
      run: |
        nohup kubectl port-forward service/rickmorty 8081:80 > portforward.log 2>&1 &
        sleep 10
        curl -v --fail http://localhost:8080/rickmorty/healthcheck
        curl -v --fail http://localhost:8080/rickmorty/characters

